/** Workspace 领域唯一公开出口（基线 §6：对外只经 index.ts 导出）。 */
export type {
  AuthPhase,
  BoardColumn,
  BoardColumnKey,
  ConnectionState,
  Runtime,
  Task,
  TaskContext,
  TaskMessage,
  TaskMessageType,
  TaskStatus,
  WorkspaceAgent,
  WorkspaceAgentStatus,
  WsEvent,
} from "./types";
export { BOARD_COLUMNS } from "./types";
export {
  runtimeSchema,
  taskContextSchema,
  taskMessageEventPayloadSchema,
  taskMessageSchema,
  taskMessageTypeSchema,
  taskStatusSchema,
  workspaceAgentSchema,
  workspaceAgentStatusSchema,
  workspaceTaskSchema,
  wsEnvelopeSchema,
  wsEventSchema,
} from "./schema";
export {
  AgentRoster,
  LoginGate,
  RuntimeStatusBar,
  TaskBoard,
  TaskCard,
  TaskCreateForm,
  TaskDetailPanel,
  MAX_RENDERED_MESSAGES,
  TASK_STATUS_META,
  formatTaskTime,
  type AgentRosterProps,
  type LoginGateProps,
  type RuntimeStatusBarProps,
  type TaskBoardProps,
  type TaskCardProps,
  type TaskCreateFormProps,
  type TaskDetailPanelProps,
} from "./components";
